/* eslint-disable max-len */
window.languages = {};

window.languages.en = {
  'users.all': 'All users',
  'user.alreadyExists': 'User exists already!',
  'user.notFound': 'User not found',
  clientNumber: 'Client Number',
  userUpdatedSuccessfully: 'User updated successfully!',
  userId: 'User Id',
  guest: 'Guest',

  'profile.save': 'Save profile',
  'profile.edit': 'Edit profile',
  'profile.edit.success': 'Profile updated successfully!',

  'app.pageNotFound': 'The requested page was not found!',
  profile: 'Profile',
  'account.my': 'My Account',
  firstName: 'First name',
  lastName: 'Last name',
  name: 'Name',
  path: 'Path',
  discountPercentage: 'Discount (%)',
  addDiscount: 'Add Discount',
  removeDiscount: 'Remove Discount',
  companyName: 'Company',
  addressLine1: 'Address Line 1',
  'address.notValid': 'Address is not valid!',
  addressLine2: 'Address Line 2',
  country: 'Country',
  'country.notValid': 'Please choose a country!',
  stateProvince: 'State/Province',
  city: 'City',
  'city.notValid': 'Please add a valid city!',
  zip: 'ZIP',
  'zip.notValid': 'Please add a valid ZIP code!',
  phone: 'Phone',
  'phone.notValid': 'Please add a valid phone number!',
  messages: 'Messages',
  notifications: 'Notifications',
  email: 'E-mail',
  'email.address': 'E-mail Address',
  'email.notValid': 'E-mail is not valid!',
  password: 'Password',
  resetPassword: 'Reset Password',
  'password.notValid': 'Password should be at least 8 characters!',
  'password.forgot': 'Forgot password?',
  'password.shouldMatch': 'The passwords do not match!',
  repeatPassword: 'Repeat Password',
  'password.resetSuccessful': 'Password reset successfully!',
  'password.UpdatedSuccessfully': 'Password updated successfully!',
  typeNewPassword: 'Please type your new password',
  typeCurrentPassword: 'Please type your current password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  repeatNewPassword: 'Repeat New Password',
  setNewPassword: 'Set new password',
  needToAcceptAllTermsToContinue:
    'You need to accept all required terms to continue!',
  login: 'Login',
  'login.alreadyAccount': 'Do you already have an account?',
  logout: 'Logout',
  signUp: 'Sign Up',
  'signUp.noAccount': "Don't have an account? Join now!",
  'signUp.successfulRegistration':
    'Thanks! Your registration was successful. Please verify your e-mail!',
  'signUp.successfulVerification': 'E-mail verified successfully!',
  'signUp.verificationError':
    'The verification link is wrong or your e-mail is already verified!',
  EN: 'EN',
  DE: 'DE',
  home: 'Home',
  filter: 'Filter',
  search: 'Search',
  clearSearch: 'Clear Search',
  'pages.my': 'My pages',
  'pages.all': 'All pages',
  'field.required': 'This field is required!',
  'field.notValidOrRequired': 'This field is not valid!',
  'name.invalid': 'Name should be at least 2 letters!',
  'ccNames.invalid': 'The requested full name is not valid!',
  'alphanumeric.invalid': 'Only alphanumeric fields are allowed!',
  by: 'by',
  or: 'or',
  and: 'and',
  up: 'Up',
  down: 'Down',
  collapse: 'Collapse',
  expand: 'Expand',
  createNew: 'Create New',
  'sorting.bestMatch': 'Best Match',
  'sorting.date': 'Newest',
  'sorting.price': 'Price',
  sortBy: 'Sort by',
  noSorting: 'No Sorting',
  'view.tiles': 'Tiles view',
  'view.list': 'List view',
  shoppingCart: 'Shopping cart',
  fullNames: 'Full Names',

  order: 'Order',
  'order.my': 'My Order',
  orders: 'Orders',
  'orders.my': 'My Orders',
  'orders.all': 'All Orders',
  'orders.frontendPrice': 'Frontend Price',
  'orders.date': 'Order Date',
  'orders.myLocal': 'My local orders',
  'orders.notFound': 'No orders found!',
  'orders.noteToCustomer': 'Notice for customer',
  'order.date': 'Order Date',
  contactCustomerSupport:
    'Payment could not be established, or is already finished. Please try again later or contact our customer support!',

  'orderStatus.placed': 'Order placed',
  'orderStatus.paid': 'Paid (Awaiting shipment)',
  'orderStatus.processing': 'Order is being processed',
  'orderStatus.processed': 'Order processed',
  'orderStatus.shipped': 'Shipped',
  'orderStatus.finished': 'Finished',
  'orderStatus.canceled': 'Cancelled',
  processingPayment: 'Processing payment...',
  usePayment: 'Use payment',

  load: 'Load',
  cancel: 'Cancel',
  security: 'Security',

  status: 'Status',
  accept: 'Accept',

  reset: 'Reset',
  resetItem: 'Reset Item',
  done: 'Done',
  add: 'Add',

  cart: 'Cart',
  'cart.empty': 'Your Cart is Empty!',
  'cart.orderSummary': 'Order summary',
  'cart.add': 'Add To Cart',
  'cart.view': 'View Cart',
  'cart.added': 'Item Added To Cart!',
  'cart.sureToDeleteItem': 'Do you want to remove this from your cart?',
  'cart.itemsTotal': 'Items Total',
  'cart.subTotal': 'Subtotal',
  'cart.cashOnDeliverLocalOnlyWarning':
    'Cash on delivery is not available for overseas products. Please remove the product from the cart or choose another payment method!',
  'cart.preparingPayment': 'Preparing payment...',
  'cart.placeOrder': 'Place Order',
  'cart.orderTotal': 'Order Total',
  'cart.shipmentAndPayment': 'Shipment and Payment',
  'cart.itemsInCart': 'Items in Cart',
  needInternetToPlaceOrder: 'You need internet to place an order',
  restartTheApp:
    'If you are online please refresh the page or restart the app.',

  individualNote: 'Notes and comments',
  net: 'Net',
  gross: 'Gross',

  total: 'Total',
  orderSum: 'Order sum',
  sum: 'Sum',
  payments: 'Payments',
  paidOrders: 'Paid orders',
  revenue: 'Revenue',
  websiteVisits: 'Website visits',
  unique: 'Unique',
  productViews: 'Product views',
  customers: 'Customers',
  verified: 'Verified',
  notVerified: 'Not Verified',
  website: 'Website',

  payment: 'Payment',
  paymentMethod: 'Payment Method',
  'payment.methodRejected':
    'This item can not be paid with this payment method!',
  pleaseSelectPaymentMethod: 'Please select a payment method...',
  placedOrderSuccessfully:
    'THANK YOU! You placed your order successfully! \uD83D\uDE0A',
  processOrderReceiveAdditionalInformation:
    'We will process your order very soon. You will receive additional information.',
  receivePaymentRequest:
    'You will receive a payment request via e-mail or SMS within 24 hours.',

  item: 'Item',
  item_plural: 'Items',
  'item.referenceNumber': 'Product code',
  outOfStock: 'Out of stock',
  'item.itemNotFound': 'Item not found',
  'item.productLocation': 'Product Location',
  'item.local': 'Local',
  'item.abroad': 'Overseas',
  'item.deliveryIn': 'Delivery in',
  'deliveryUnit.businessDays': 'Business days',
  'deliveryUnit.hours': 'Hour',
  'deliveryUnit.hours_plural': 'Hours',
  'deliveryUnit.minutes': 'Minute',
  'deliveryUnit.minutes_plural': 'Minutes',
  'item.selectOptions': 'Select options',
  'item.productEditedSuccessfully': 'Product edited successfully',
  'items.notFound': 'No items found',
  'items.variants': 'Variants',
  'items.optionName': 'Option Name',
  'item.combination': 'Combinations',
  'item.addPriceCombination': 'Add Price Combination',
  'item.additional': 'Additional',
  'item.localProduct': 'Local Product',
  'item.dimensions': 'Item Dimensions',
  'item.weight': 'Item Weight',
  referenceNumber: 'Reference Number',
  addReferenceNumber: 'Add Reference Number',
  length: 'Length',
  height: 'Height',
  width: 'Width',
  weight: 'Weight',
  selectOptions: 'Select options',
  quantityUnits: 'Quantity Units',
  plural: 'Plural',
  singular: 'Singular',
  cm: 'cm',
  kg: 'kg',
  per: 'per',

  'products.viewAll': 'View All Products',

  products: 'Products',
  'products.all': 'All Products',
  'products.number': 'Product Number',
  'products.referenceNumber': 'Reference Number',
  uniqueViewers: 'Unique Viewers',
  totalProductViews: 'Total Product Views',
  views: 'Views',
  uniqueVisits: 'Unique visits',
  totalVisits: 'Total Visits',
  uniqueVisitors: 'Unique Visitors',
  productStatus: 'Product Status',
  dynamicFetchImages: 'Dynamic Fetch Images',
  fetching: 'Fetching...',
  fetched: 'Fetched!',
  staticFetchImages: 'Static Fetch Images',

  image: 'Image',
  notFoundImage: 'No Image Found',
  images: 'Images',
  exclusive: 'Exclusive',
  availableImages: '{{count}} available image',
  availableImages_plural: '{{count}} available images',
  chooseImageFromProduct: 'Choose image from product',
  sureToDeleteImage: 'Do you really want to remove this image?',

  loadImageByUrl: 'Load Image from Url',
  uploadImage: 'Upload Image',
  uploading: 'Uploading...',
  isDirectUpload:
    'Direct Upload. (Upload the picture in original size without any editing)',

  loading: 'Loading...',

  period: 'Period',

  variants: 'Variants',
  'variants.add': 'Add variant',

  lastUpdate: 'Last Update',

  createdAt: 'Created At',

  editItem: 'Edit Item',
  edit: 'Edit',
  remove: 'Remove',
  checkItOut: 'Check it out',
  continueEdit: 'Continue editing',
  viewList: 'View list',

  delete: 'Delete',
  deliveryTimeInBusinessDays: 'Delivery time in business days',
  deliveryTimeOutOfStock: 'Delivery time when out of stock (Order in Advance)',

  save: 'Save',
  noParent: 'No Parent',
  itemQuantity: 'Item quantity',
  en: 'EN',
  de: 'DE',

  ok: 'Ok',
  new: 'New',
  view: 'View',
  roles: 'Roles',
  role: 'Role',

  emailSent: 'E-mail sent!',
  sendingEmailError: 'Error on sending e-mail!',
  sendingEmail: 'Sending e-mail...',
  sendAgainVerificationEmail: 'Send again verification e-mail',

  sortArrowUp: 'Sort arrow up',
  sortArrowDown: 'Sort arrow down',

  textInput: 'Text input',

  errorPlacingOrder:
    'We got a error while placing your order. Please try again later or contact our support team!',
  connectionErrorQuestionForLocalOrder:
    'We could not establish a connection. Do you want to save the order in your local orders? You can then just send this order at any time when a connection available.',

  aboveImageSizeAllowed: 'Image size is above allowed size!',
  addImageUrl: 'Use Direct Image Url',
  enterUrlFields: 'Please enter the url fields',
  enterImageUrlToBeAddedIntoProductImages:
    'Please enter the url of the image, to be added into your product images.',
  productAddedSuccessfully: 'Product added successfully',

  requestLinkSent: 'Request link sent! Please check your e-mail',

  sendVerificationLink: 'Send Verification Link',

  allLocalStorageDataCleared: 'All local storage data cleared!',
  cleanAllLocalData: 'Clean all local data',

  sku: 'SKU',
  addSku: 'Add SKU',
  inventory: 'Inventory',
  noInventory: 'No Inventory',
  availableAmount: 'Available Amount',
  sold: 'Sold',
  chooseStore: 'Choose Store',
  selectedStore: 'Selected Store',

  editor: 'Editor',
  enterOptionSetDetails: 'Enter a Option and Set Details',
  optionSetEditor: 'Option Set Editor',
  addonEditor: 'Add-On Editor',
  enterAddonDetails: 'Enter Add-On Details',
  addons: 'Add-Ons',
  noAddonsAvailable: 'No Add-Ons Available',

  noOwnPrices: 'No set prices',
  yes: 'Yes',
  no: 'No',
  back: 'Back',
  optionEditor: 'Option Editor',
  useGlobalTags: 'Use Global Tags',
  useGlobalTagGroups: 'Use Global Tag Groups',
  useGlobalAttribute: 'Use Global Attribute',
  useGlobalOptions: 'Use global option',
  removeGlobalOption: 'Remove global option',
  globalOption: 'Global option',
  globalOptions: 'Global options',
  addOption: 'Add Option',
  addVariant: 'Add Variant',
  addTag: 'Add Tag',
  addTagGroup: 'Add Tag Group',
  addAttribute: 'Add attribute',
  editOption: 'Edit Option',
  editVariant: 'Edit Variant',
  editTag: 'Edit Tag',
  editTagGroup: 'Edit Tag Group',
  editAttribute: 'Edit Attribute',
  globalAttributes: 'Global Attributes',
  tagGroups: 'Tag Groups',
  tags: 'Tags',
  attributeSuccessfullyCreated: 'Attribute successfully created!',
  attributeSuccessfullyUpdated: 'Attribute successfully updated!',
  useInFilter: 'Use in filter',
  variantEditor: 'Variant Editor',
  optionSets: 'Option Sets',
  chooseOptionSets: 'Choose Option Sets',
  selectAll: 'Select All',
  sureToCreateNewOption:
    'Do you want to create new option? This action will remove all current option sets!',
  pricesSet: 'Prices set',
  addPrices: 'Add prices',
  removePrices: 'Remove prices',
  enterVariantDetails: 'Enter Variant Details',
  useGlobalVariants: 'Use global variant',
  removeGlobalVariant: 'Remove global variant',
  enterOptionDetails: 'Enter Option Details',
  enterTagDetails: 'Enter Tag Details',
  enterTagGroupDetails: 'Enter Tag Group Details',
  enterAttributeDetails: 'Enter Attribute Details',
  sureToDeleteVariant: 'Are you sure you want to delete this variant?',
  sureToDeleteTag: 'Are you sure you want to delete this tag?',
  sureToDeleteTagGroup: 'Are you sure you want to delete this tag group?',
  sureToDeleteAddon: 'Are you sure you want to delete this Add-On?',
  sureToDeleteAttribute: 'Are you sure you want to delete this attribute?',
  sureToDeleteOption:
    'Are you sure you want to delete this option? This will remove also all option sets!',
  sureToDeleteOptionSet: 'Are you sure you want to delete this option set?',
  pricesAndOptions: 'Prices and Options',
  options: 'Options',
  product: 'Product',
  shippingFee: 'Shipping fee',
  freeShipping: 'Free shipping',
  shippingMethods: 'Shipping methods',
  shippingName: 'Shipping name (e.g. DHL, UPS)',
  letDelivered: 'let it be delivered',
  pickUp: 'Pick up',
  usePickUp: 'Use Pick Up',
  pickUpPrice: 'Pick up price',
  shippingAddress: 'Shipping address',
  shippingInformation: 'Shipping Information',
  shippingAddressSameAsBillingAddress:
    'Shipping address is the same as billing address',
  quantity: 'Quantity',
  addedToWishList: 'Item Added To Wish List',
  viewWishList: 'View Wish List',
  buyNow: 'Buy',
  goToOrder: 'Order',
  price: 'Price',
  originalPrice: 'Original Price',
  originalUrl: 'Original URL',
  continueShopping: 'Continue Shopping',
  sureToRemoveItem: 'Do you want to remove this item permanently?',
  wishList: 'Wish List',
  wishListItems: 'Items in Wishlist',
  wishListEmpty: 'Your Wish List is Empty!',
  sureToDeleteItemWishList: 'Do you want to remove this from your wish list?',
  placeOrder: 'Place Order',
  newItem: 'New item',
  addProductItem: 'Add Item',
  addItem: 'Add Item',
  addNewItem: 'Add new item',
  addNewProduct: 'Add new product',
  updateItem: 'Update item',
  areYouSureToResetItem:
    'Are you sure you want to reset all changes on this item?',
  title: 'Title',
  description: 'Description',
  metaKeywords: 'Meta Keywords',
  noRecords: 'No records',
  noEntries: 'No entries',

  paymentMethods: 'Payment Methods',
  addPaymentMethod: 'Add Payment Method',
  areYouSureToRemovePaymentSettings:
    'Are you sure you want to remove the settings of this payment method? This action is irreversible!',
  settingsSuccessfullyRemovedFromServer:
    'Settings successfully removed from the server!',
  settingsCouldNotBeRemoved: 'Settings could not be removed!',
  paymentSettings: 'Payment Settings',
  activeSettings: 'Settings are active',
  noActiveSettings: 'Settings are not active',
  noPaymentWarning:
    'You need to add a payment method, else ordering is not possible.',
  areYouSureToRemovePayment: 'Are you sure you want to remove this payment?',
  selectedPayment: 'Selected Payment',
  // Not used yet
  addPaymentProvider: 'Add Payment Provider',
  choosePaymentProviderToAdd:
    'Important! Some of the payment methods may need additional configuration to work. This additional configuration will be displayed above all payment methods.',
  creditCard: 'Credit Card / Debit Card',
  stripe: 'Stripe',
  microPaymentCreditCard: 'Credit Card / Debit Card',
  microPaymentSofort: 'Online bank transfer',
  microPaymentDirectDebit: 'Direct Debit',
  micropayment: 'Micropayment',
  payOnPickup: 'Pay On Pickup',
  payOnPickupContent: 'Pay when you pick up the order',
  coinsPH: 'Coins.PH',
  coinsPHContent:
    'Pay at 7-Eleven, Cebuana Lhuillier, M Lhuillier or with Coins.ph',
  localCashOnDelivery: 'Cash On Delivery',
  localCashOnDeliveryContent: 'Cash On Delivery / Local Products Only',
  localOnly: 'Local Only',
  paypal: 'Paypal',
  vivaWallet: 'Viva Wallet',
  vivaWalletCreditCard: 'Credit Card / Debit Card',
  vivaWalletSofort: 'Direct Debit',
  pay: 'Pay',
  cashOnDelivery: 'Cash On Delivery',
  cashOnDeliveryContent: 'Pay comfortable when you receive the order',

  stripeSettingsEditingText:
    'The Stripe settings will be immediately stored into the server.',
  stripeSettings: 'Stripe settings',
  stripeSecretKey: 'Secret key',
  stripeEndpointSecret: 'Signing Secret',
  stripePushableKey: 'Publishable key',
  webhookStripe: 'Add the following URL as webhook to your stripe account',
  settingsSuccessfullyUpdatedToServer:
    'Settings were successfully updated to the server!',
  micropaymentSettings: 'Micropayment Settings',
  testMode: 'Test mode',
  micropaymentSettingsEditingText:
    'The micropayment settings will be immediately stored into the server.',
  'micropayment.projectId': 'Project Id / Kennung',
  accessKey: 'Access Key',
  paypalSettings: 'PayPal Settings',
  paypalSettingsEditingText:
    'The PayPal settings will be immediately stored into the server.',
  clientId: 'Client Id',
  clientSecret: 'Client Secret',
  mode: 'Mode',
  webhookMicropayment:
    'Add the following URL as a Notification URL to your micropayment payments',
  vivaWalletSettings: 'Viva Wallet Settings',
  vivaWalletEditingText:
    'The Viva Wallet settings will be immediately stored into the server.',

  buyerGuarantee: 'Buyer Guarantee',
  addTrackingNumber: 'Add tracking number',
  orderNumber: 'Order Number',
  orderN: 'Order # ',
  totalPrice: 'Total price',
  expectedDelivery: 'Expected delivery',
  trackingNo: 'Tracking No.',
  saveChanges: 'Save changes',
  details: 'Details',
  orderUpdateSuccessful: 'Order updated successfully!',
  backToOrders: 'Back to orders',
  deleteLocalOrder: 'Are you sure you want delete this local order?',
  localOrder: 'Local Order',
  orderAmount: 'Order amount',
  removeOrder: 'Remove order',
  checkOrder: 'Check order',
  contactSupportTeam: 'Please try again, or contact our customer support team!',
  contact: 'Contact',
  chooseConvenient: 'Please choose the most convenient way to contact us',
  sendDm: 'Send us a direct message',

  keywords: 'Keywords',

  inactive: 'Inactive',
  active: 'Active',

  asc: 'Up',
  desc: 'Down',

  gt: 'greater than',
  gte: 'greater or equal',
  lt: 'lower than',
  lte: 'lower or equal',
  eq: 'is equal',
  gt_symbol: '>',
  gte_symbol: '≥',
  lt_symbol: '<',
  lte_symbol: '≤',
  eq_symbol: '=',

  itemsWeight: 'Items weight',
  itemsSum: 'Items sum',
  productOwnShipping: 'Product own shipping',
  productOwnShippingDescription:
    "This shipping method will be calculated with the product's own shipping prices. See Edit Product ➡ Prices.",

  recommendedProducts: 'Recommended Products',
  similarProducts: 'Similar Products',
  returnPolicy: 'Return Policy',
  privacyPolicy: 'Privacy Policy',
  termOfUse: 'Terms of Use',
  shippingPolicy: 'Shipping Policy',
  becomePartner: 'Become a Partner',
  copyRight: 'Copyright ©',
  close: 'Close',
  shippingProfiles: 'Shipping profiles',
  addPriceShippingAndAllTaxes:
    'Add prices for shipping including all taxes (if taxes applicable)',

  categories: 'Categories',
  account: 'Account',
  administration: 'Administration',
  dashboard: 'Dashboard',
  allCategories: 'All Categories',
  contactUs: 'Contact Us',
  onBoarding: 'Onboarding',
  addCategory: 'Add Category',
  areYouSureToRemoveThisCategory:
    'Are you sure you want to remove this category?',

  shipping: 'Shipping',
  address: 'Address',
  address_plural: 'Addresses',
  'shipping.selectAddress': 'Please select shipping address...',
  'shipping.enterAddress': 'Please enter address and billing information...',
  'shipping.shipTo': 'Ship To',
  'shipping.buyerAddress': 'Buyer Address',
  'shipping.buyerData': 'Buyer and Invoice Data',
  areYouSureToDeleteAddress:
    'Are you sure you want PERMANENTLY delete this address?',
  'address.new': 'New address',
  saveAddress: 'Save Address',
  billingAddress: 'Billing address',
  useAddress: 'Use Address',
  shippingAddresses: 'Shipping addresses:',
  addressNotValid: 'Address not valid',

  willBeCalculated: 'Will be calculated',
  isLoading: '...is loading',
  pleaseEnterAgainAddressData: 'Please enter address data again!',
  enterShippingData: 'Enter Shipping Data',
  editShippingData: 'Edit Shipping Data',
  removeShippingData: 'Remove Shipping Data',
  confirm: 'Confirm',
  needToBeOnlineForThisShippingMethod:
    'You need to be online for this shipping method!',
  shippingOrderId: 'External Order Id',
  tracking: 'Tracking',
  billOfLoad: 'Bill Of Load',
  create: 'Create',
  open: 'Open',
  notFound: 'Not Found!',
  valueWhenNoConditionMet: 'Amount, if no condition met',
  hideMobile: 'Hide on mobile devices',
  showMobile: 'Show on mobile devices',
  hideDesktop: 'Hide on desktop devices',
  showDesktop: 'Show on desktop devices',
  selectConditions: 'Select Conditions',
  hidingConditions: 'Hiding Conditions',
  'hidingConditions.searchTerm': 'Active Search',
  'hidingConditions.otherPages': 'Pages > 1',
  internalNote: 'Internal Note',
  addNote: 'Add Note',
  history: 'History',
  noHistory: 'No History found',
  internalCorrespondence: 'Internal Correspondence',
  customerCorrespondence: 'Customer Correspondence',
  errorWhileAddingNote: 'Error while adding note',
  orderNotFound: 'Order not found!',
  econt: 'ECONT',
  pleaseEnterDataFor: 'Please enter data for $t({{provider}})',
  shippingProviderSettings: 'Data for $t({{provider}})',
  shopId: 'Shop ID',
  privateKey: 'Private Key',

  store: 'Store',
  stores: 'Stores',
  storeNumber: 'Store Number',
  storeName: 'Store Name',
  addStore: 'Add Store',
  editStore: 'Edit Store',
  areYouSureToRemoveThisStore:
    'Are you sure you want to remove this store? Removing the store will cause removal of all item quantities!!!',

  vat: 'VAT',
  displayedVatName: 'VAT Name (e.g. "VAT. 20%")',
  vatPercentage: 'VAT Percentage',
  includingVAT: 'Including VAT',
  pricesIncludingVAT: 'All prices including VAT',
  vatProfiles: 'VAT Profiles',
  productVatProfile: 'Product VAT Profile',
  vatSettings: 'VAT Settings',
  vatInactive: 'VAT Deactivated',
  vatActive: 'VAT Active',
  vatSettingsText:
    'Configure the VAT Behavior of your shop. Use field active to enable/disable VAT for the shop.',
  includedInPrice: 'Included in price',
  shippingTaxProfile: 'VAT used for shipping',

  useInventory: 'Use Inventory',
  inventorySettings: 'Inventory Settings',
  inventoryActive: 'Inventory Active',
  inventoryInactive: 'Inventory Inactive',
  inventorySettingsText:
    'Configure the inventory system of your shop. Use the field "Use Inventory" to activate the Inventory.',

  permanentlyDeleteThisProfile:
    'Are you sure you want to PERMANENTLY delete this profile?',
  then: 'THEN',
  defaultValue: 'Default value',
  offerValue: 'Offer value',
  addSpecialOffer: 'Add special offer',
  showColumns: 'Show columns',
  showMore: 'Show more',
  showLess: 'Show less',

  newProfile: 'New profile',
  addProfile: 'Add profile',
  editProfile: 'Edit profile',
  saveProfile: 'Save profile',
  noFieldSelected: 'No field selected',
  fieldNames: 'Field names',
  baseCartField: 'Base field from cart',

  addCondition: 'Add condition',
  removeCondition: 'Remove condition',
  addCase: 'Add case',
  sureToRemoveCase: 'Are you sure to delete this case?',
  removeCase: 'Remove case',
  value: 'Value',
  useGlobalFieldName: 'Use global field name',
  comparisonFieldName: 'Comparison field name',
  addComparisonOperator: 'Add comparison operator',

  addDimensions: 'Add Dimensions',
  dimensions: 'Dimensions',
  pleaseChooseDimensionsYouWantToAddToItem:
    'Please choose the desired dimensions to add to your item!',

  shopSettings: 'Shop Settings',
  adjustShop: 'Configure your shop',
  logo: 'Logo',
  colors: 'Colors',

  privacy: 'Privacy',
  'gdprConsent.active': 'Use GDPR Consent',
  'gdprConsent.inWidgets':
    'The GDPR Consent can be edited in Widgets -> GDPR Consent.',

  cache: 'Cache',
  caching: 'Caching',
  disableServiceWorker: 'Disable Service Worker',
  disableServiceWorkerMessage:
    'Disabling Service Worker means that your PWA (Progressive Web App) functionality will be fully disabled. No more efficient caching or offline functionality will be available.',

  css: 'CSS',
  customCss: 'Custom CSS',
  editCustomCss: 'CSS Editor',
  clickOutsideToView: 'Click outside editor to view changes!',
  fontFamily: 'Font Family',
  global: 'Global',
  component: 'Component',

  typography: 'Typography',
  typographyComponent: 'Typography Component',
  fontWeight: 'Font Weight',
  fontSize: 'Font Size',
  lineHeight: 'Line Height',

  main: 'Main',
  contrastText: 'Contrast Text',
  paper: 'Paper Block',
  default: 'Default',
  primary: 'Primary',
  secondary: 'Secondary',
  disabled: 'Disabled',
  hint: 'Hint',
  textColor: 'Text Color',
  elevation: 'Elevation',
  backgroundColor: 'Background Color',
  buttonBackgroundColor: 'Button Background Color',
  buttonBackgroundColorHover: 'Button Background Color Hover',

  theme: 'Theme',
  'theme.cart.usePaymentRadio': 'Use radio group for payment methods',
  'theme.editor': 'Theme Editor',
  'theme.searchField': 'Search Field',
  'theme.adjustTheme': 'Adjust Your Theme',
  'theme.activateEditing': 'Activate Editing',
  'theme.previewMode': 'Preview',
  'theme.exitPreviewMode': 'Exit Preview',
  'theme.displayAppBar': 'Display App Bar',
  'theme.displayAppBarText': 'Display App Bar Text',
  'theme.appBarHeight': 'App Bar height',
  'theme.contentAddMarginTop': 'App Bar Margin Top',
  'theme.logoWidth': 'Logo Width',
  'theme.hideLogoOnMobile': 'Hide Logo in Mobile',
  'theme.showCartMobileBottom': 'Show Cart Bottom in mobile',
  'theme.mainColors': 'Main colors',
  'theme.primaryColors': 'Primary colors',
  'theme.secondaryColors': 'Secondary colors',
  'theme.backgroundColors': 'Background colors',
  'theme.textColors': 'Text colors',
  'theme.buttonTextColors': 'Button text colors',
  'theme.themeSettings': 'Theme Settings',
  'theme.itemsLeftWidth': 'Width of items left column',
  'theme.itemsRightWidth': 'Width of items right column',
  'theme.hideSortingBar': 'Hide sorting bar of items',
  'theme.item.leftWidgetsWidth': 'Item Left Widgets Width',
  'theme.item.rightWidgetsWidth': 'Item Right Widgets Width',
  'theme.itemCardLine.cardType': 'Type of Item Card Line',
  'theme.itemCardLine.hideCardActions': 'Hide Card Actions',
  'theme.itemCardLine.showDescription': 'Show Description',
  'theme.itemCardLine.descriptionLength': 'Description max length',
  'theme.itemCardTile.hideCardActions': 'Hide Card Actions',
  'theme.defaultView': 'Default View',
  'theme.itemsH1': 'Display Head Text in Items',
  'theme.header': 'Header',
  'theme.section': 'Theme Section',
  'theme.mobileBottom': 'Mobile Bottom Bar',
  'theme.items': 'Products',
  'theme.sidebarActive': 'Sidebar active',
  'theme.hideSidebarDesktop': 'Hide sidebar for desktop',
  'theme.hideSidebarMobile': 'Hide sidebar for mobile',
  'theme.logoMarginLeft': 'Logo margin left',
  'theme.logoInsideSearch': 'Logo inside of search',
  'theme.searchFieldMaxWidth': 'Max width of search field',
  'theme.hideBuyNowButton': 'Hide Buy-Now Button',
  'theme.item.showReferenceNumber': 'Show Reference Number',
  'background.usePrimaryColor': 'Set Primary Color',

  'widgetPosition.homeTop': 'Home (Top)',
  'widgetPosition.sidebarTop': 'Sidebar (Top)',
  'widgetPosition.sidebarBottom': 'Sidebar (Bottom)',
  'widgetPosition.belowAppBar': 'Below AppBar',
  'widgetPosition.aboveAppBar': 'Above AppBar',
  'widgetPosition.aboveContent': 'Above Content',
  'widgetPosition.beforeSearch': 'Before Search',
  'widgetPosition.footer': 'Footer',
  'widgetPosition.itemsLeft': 'Items (Left)',
  'widgetPosition.itemsRight': 'Items (Right)',
  'widgetPosition.itemsTop': 'Items (Top)',
  'widgetPosition.itemsFilterDrawer': 'Items Filter Drawer',
  'widgetPosition.item': 'After Product',
  'widgetPosition.itemInside': 'In Product Content',
  'widgetPosition.itemLeft': 'Product (Left)',
  'widgetPosition.itemRight': 'Product (Right)',
  'widgetPosition.signUpTerms': 'Sign Up Terms',
  'widgetPosition.gdprConsent': 'GDPR Consent Details',
  'widgetPosition.gdprConsentTeaser': 'GDPR Consent Teaser',
  'widgetPosition.global': 'Global',
  'widgetPosition.aboveContainer': 'Above Page Content',

  'widgetType.html': 'Pure HTML OR MD',
  'widgetType.checkboxWithHtml': 'Checkbox with HTML',
  'widgetType.categories': 'Categories',
  'widgetType.attributes': 'Filter',
  'widgetType.cart': 'Cart',
  'widgetType.staticPages': 'List Of Static Pages',
  'widgetType.copyRight': 'Copyright',
  'widgetType.homeLink': 'Home Button',
  'widgetType.similarProducts': 'Similar Products',
  'widgetType.accordionIconText': 'Accordion Icon and Text',
  'widgetType.image': 'Image',
  'widgetType.grid': 'Grid Elements',
  'widgetType.slider': 'Slider',

  'widgets.showTitle': 'Show title',
  'widgets.openByDefault': 'Open By Default',
  'widgets.widgetType': 'Widget Type',
  'widgets.subtype': 'Widget variant',
  'widgets.isRequired': 'Is Required',
  'widgets.checkedByDefault': 'Checked by default',
  'widgets.arrows': 'Arrows',
  'widgets.swipeToSlide': 'Swipe To Slide',
  'widgets.draggable': 'Draggable',
  'widgets.dots': 'Dots',
  'widgets.animationSpeed': 'Animation Speed',
  'widgets.arrowSize': 'Arrow Size',
  'widgets.slideAnimation': 'Slide Animation',
  'widgets.autoplay': 'Autoplay',
  'widgets.autoplaySpeed': 'Autoplay Speed',
  'widgetSubtype.none': 'Default',
  'widgetSubtype.horizontal': 'Horizontal',
  'widgetSubtype.sidebar': 'Sidebar',
  'widgetSubtype.footer': 'Footer',

  noWidgets: 'No Widgets',
  widgetPosition: 'Widget Position',
  addWidget: 'Add Widget',
  widgetsContent: 'Widget Contents',
  areYouSureToRemoveWidget: 'Are you sure you want to remove this widget?',

  'slideAnimation.fade': 'Fade',
  'slideAnimation.slide': 'Slide',

  gridItems: 'Grid Items',
  noGridItems: 'No Grid Items',
  containerClassName: 'Container Class Name',
  gridItemContent: 'Grid Item Content',
  customClassName: 'Custom Class Name',
  widthMobile: 'Mobile Width',
  widthTablet: 'Tablet Width',
  widthDesktop: 'Desktop Width',
  containerSpacing: 'Container Spacing',
  alt: 'Alt Attribute',
  imageClass: 'Custom Image Class Name',
  linkClass: 'Custom Link Class Name',
  draft: 'Draft',
  saveDraft: 'Save Draft',
  draftSavedSuccess: 'Draft saved successfully!',
  draftRemoveSuccess: 'Draft removed successfully!',
  draftFoundMessage: 'You have a draft!',
  sureToDeleteDraft: 'Are you sure you want to delete this draft?',
  settingsSuccessfullyLoaded: 'Settings successfully loaded!',

  seo: 'SEO',
  'seo.ogImage': 'Meta Og Image',
  'seo.favicon': 'Favicon',
  'seo.appleTouchIcon': 'Apple Touch icon in 192px',
  'seo.title': 'Meta Title',
  'seo.description': 'Meta Description',
  'seo.keywords': 'Meta Keywords',
  'seo.themeColor': 'Theme Color',

  app: 'App',
  'app.title': 'App Title',
  'app.url': 'App Url',
  'app.appName': 'App Name',
  'app.copyrightName': 'Copyright Title',

  'config.section': 'Config Section',

  bulkPercentagePricing: 'Bulk Percentage Pricing',
  percentage: 'Percentage',
  changePrices: 'Change Prices',
  pricesUpdateSuccess: 'Prices updated successfully!',
  pricesUpdateError: 'Error while updating prices!',
  areYouSureToUpdateAllPrices:
    'Are you sure you want to update all prices? This action will have immediate effect!',
  examplePriceChange: 'Example Price Change',
  chooseCategory: 'Choose Category',

  icon: 'Icon',
  'icon.verified_user': 'Verified',
  'icon.local_shipping': 'Shipping',
  'icon.info': 'Info',
  'icon.check_outlined': 'Check in circle',
  'icon.check': 'Check',
  'icon.warning': 'Warning',

  appInfo: 'App Info',
  deployChanges: 'Deploy',
  chooseImage: 'Choose Image',
  configuration: 'Configuration',
  widgets: 'Widgets',
  itemCardLine: 'Item Card Line',
  itemCardTile: 'Item Card Tile',
  regular: 'Standard',
  smallThumbnail: 'Small Thumbnail',
  noThumbnail: 'No Thumbnail',

  fitToCrop: 'Fit to crop',
  dragOrClickToUpload: 'Drag or click to load',
  formatSquareImage: 'Fit Image to Square (Recommended for Product Images)',
  fillImageBackground: 'Fill Image Background with Color',
  imageBackgroundColor: 'Image Background Color',
  crop: 'Crop',
  removeBackground: 'Remove Background',
  square: 'Square',
  landscape: 'Landscape',
  headerImage: 'Header Image',
  banner: 'Banner',
  portrait: 'Portrait',
  custom: 'Custom',
  shape: 'Shape',
  zoom: 'Zoom',
  rotate: 'Rotate',
  selectElementToEdit: 'Select Element to Edit',
  fitBackground: 'Fit Background',
  addImage: 'Add Image',
  addText: 'Add Text',
  styles: 'Styles',
  opacity: 'Opacity',
  fill: 'Fill',
  stroke: 'Stroke',
  stickers: 'Stickers',
  fineTune: 'Fine-tune',
  sureToResetImage: 'Are you sure you want to reset the image?',
  sureToLoadNewImage: 'Are you sure you want to load new image?',
  backgroundRemoval: 'AI Background Removal',
  useAlphaMatting: 'Use Alpha Matting',
  foregroundThreshold: 'Foreground Threshold',
  backgroundThreshold: 'Background Threshold',
  erodeStructureSize: 'Erode Structure Size',
  mattingBaseSize: 'Matting Base Size',
  changePreviewColor: 'Change Preview Background Color',

  Sepia: 'Sepia',
  Grayscale: 'Grayscale',
  Brownie: 'Brownie',
  Vintage: 'Vintage',
  Kodachrome: 'Kodachrome',
  Technicolor: 'Technicolor',
  Polaroid: 'Polaroid',
  Blur: 'Blur',
  Brightness: 'Brightness',
  Contrast: 'Contrast',

  pages: 'Pages',
  addPage: 'Add Page',

  imageItems: 'Image Elements',
  element: 'Element',
  none: 'None',
  openInNewWindow: 'Open in new window',
  addUrl: 'Add Link',
  link: 'Link',
  url: 'URL',
  color: 'Color',
  text: 'Text',
  settings: 'Settings',
  expertSettings: 'Expert Settings',
  simplifiedSettings: 'Simplified Settings',
  shopUpdatedSuccessfully: 'Shop System Updated Successfully!',
  sureToUpdateShop:
    'Are you sure you want to update all shop settings? This action will take immediate effect!',
  textOnly: 'Primary Text',
  buttonOutlinedText: 'Button Outlined',
  areYouSure: 'Are you sure?',

  today: 'Today',
  thisWeek: 'This Week',
  thisMonth: 'This Month',
  last3Months: 'Last 3 Months',
  last6Months: 'Last 6 Months',
  thisYear: 'This Year',

  'newVersionDetected.refresh':
    'A new version was detected. Do you want to update now?',
  newShopVersionAvailable:
    'There is a new version available! Would you like to upgrade now?',
  newAppVersionAvailable:
    'The shop was updated! Update your local app version.',
  newAppVersionAvailableInfo:
    'Close all other tabs and refresh the website a few times to update your app!',
  update: 'Update',
  generateAppFilesAnyway: 'Generate APP Files Anyway',
  sureToGenerateApp: 'Are you sure you want to generate app files?',
  shopUpdateTooOften:
    'You are trying to generate new files too often! Please try again in few minutes.',
  updating: 'Updating',
  updateNow: 'Update Now',
  usedVersion: 'Used Version',
  refreshNow: 'Refresh Now',
  shopIsUpToDate: 'Your shop is up to date!',
  currentShopVersion: 'Current Shop Version',
  latestVersion: 'Latest Version available',

  importProducts: 'Import Products',
  initiateImport: 'Initiate Import',
  sureToInitiateImport: 'Are you sure you want to initiate import?',
  successfullyImportProducts: 'Successfully imported products',
  errorOnImport: 'Error while importing products!',

  errorMessage: 'Error message',
  'errorDescription.url': 'The given URL is not valid!',
  'errorDescription.title':
    'Title is required and should be max 250 characters!',
  'errorDescription.description':
    'Description is required and should be max 1500 characters!',
  'errorDescription.prices':
    'Prices are required and should be bigger or equal 0!',
  'errorDescription.originalPrice':
    'Prices should be a number (not empty field)!',
  'errorDescription.images': 'At least 1 picture should be uploaded!',
  'errorDescription.password': 'Password should be at least 8 characters!',
  'errorDescription.email': 'E-mail not valid!',
  'errorDescription.optionSets': 'There is an error with your option sets!',
  'errorDescription.options':
    'There is an error with your options! There should be no empty fields.',
  'errorDescription.variants':
    'There is an error with your variants! There should be no empty fields.',
  'errorDescription.onChanges': 'There is an error on saving changes!',
  'error.CATEGORY_ALREADY_EXISTS': 'Category already exists! Try another key.',
  'error.CATEGORY_PARENT_SELF': 'Category can not be self-parent.',

  'error.unknown': 'Unknown error!',
  'error.IMAGE_ERROR': 'Error while trying to process image!',
  'error.ACTION_DEACTIVATED': 'Action is deactivated at the moment!',
  'error.FTP_ERROR': 'Error during FTP Transfer! Files could not be uploaded!',
  'error.ATTRIBUTE_IN_USE':
    'The attribute is used by a product and can not be removed!',
  'error.USER_WRONG_PASSWORD': 'The given password is wrong!',
  'error.USER_WRONG_LOGIN_CREDENTIALS': 'Wrong login credentials!',
  'error.USER_NOT_VERIFIED': 'E-mail not verified yet!',
  'error.USER_NOT_ALLOWED': 'User account is not active or banned!',
  'error.USER_LOGIN_ATTEMPT_EXCEEDED':
    'Too many login attempts! Please try again after 15-30 Minutes, or contact us!',
  'error.USER_REQUEST_TOO_OFTEN':
    'We received too many requests! Please try again later!',
  'error.ORDER_ITEMS_CHANGE':
    'Items were updated. Meanwhile, please check the new price and confirm again!',
  'error.INVALID_REQUEST': 'The request is not valid or is expired!',
  'error.EMAIL_CAN_NOT_BE_SEND':
    'We experienced an error while sending e-mail. Please try again later!',
  'error.STORAGE_LIMIT_EXCEEDED':
    'The storage limit was exceeded. Please remove some files or contact our support team!',
  'error.IMAGE_UPLOAD_ERROR': 'Error while trying to upload image!',
  'error.SIZE_TOO_LARGE': 'The size is too large!',
};
